baseurl: /
auto: true
server: true

future: true
pygments: true
markdown: rdiscount

permalink: /blog/:title

rdiscount:
  extensions: [smart]

exclude: ["README.md", "TODO.md"]
include: ["42"]

# Configuration for ehancements

google_analytics:
  account: UA-31535065-1

github:
  username: unacinux
